In [53]:
import pandas as pd
import numpy as np

In [54]:
orders = pd.read_csv(r"fact_orders.csv")

### Basic Info

In [55]:
orders.head()

,order_id,customer_id,restaurant_id,delivery_partner_id,order_timestamp,subtotal_amount,discount_amount,delivery_fee,total_amount,is_cod,is_cancelled
0,ORD202501023439,CUST181110,REST08622,DP05541,2025-01-01 12:00:00,471.62,35.44,30.56,466.74,N,N
1,ORD202501012051,CUST025572,REST02383,DP08091,2025-01-01 12:00:00,255.68,0.00,27.45,283.13,Y,N
2,ORD202501019281,CUST179306,REST14069,DP02021,2025-01-01 12:00:00,428.38,0.00,26.23,454.61,N,N
3,ORD202501000124,CUST191820,REST19745,DP13859,2025-01-01 12:00:00,260.81,0.00,32.75,293.56,N,N
4,ORD202501006518,CUST033760,REST12962,DP09615,2025-01-01 12:00:00,280.33,0.00,25.57,305.90,N,N

In [56]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149166 entries, 0 to 149165
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             149166 non-null  object
 1   customer_id          149166 non-null  object
 2   restaurant_id        149166 non-null  object
 3   delivery_partner_id  143531 non-null  object
 4   order_timestamp      149166 non-null  object
 5   subtotal_amount      149166 non-null  float64
 6   discount_amount      149166 non-null  float64
 7   delivery_fee         149166 non-null  float64
 8   total_amount         149166 non-null  float64
 9   is_cod               149166 non-null  object
 10  is_cancelled         149166 non-null  object
dtypes: float64(4), object(7)
memory usage: 12.5+ MB

In [57]:
orders.describe()

       subtotal_amount  discount_amount   delivery_fee   total_amount
count    149166.000000    149166.000000  149166.000000  149166.000000
mean        314.373203        18.891589      30.069224     325.550833
std         147.346779        29.801279      10.997816     146.790190
min           0.000000         0.000000       0.000000       0.000000
25%         234.960000         0.000000      24.730000     249.842500
50%         309.070000         0.000000      31.485000     321.700000
75%         396.290000        34.690000      38.240000     406.590000
max         900.000000       222.530000      45.000000     944.910000

#### Handling Missing Value

In [58]:
orders.isnull().sum()

order_id                  0
customer_id               0
restaurant_id             0
delivery_partner_id    5635
order_timestamp           0
subtotal_amount           0
discount_amount           0
delivery_fee              0
total_amount              0
is_cod                    0
is_cancelled              0
dtype: int64

In [59]:
orders['delivery_partner_id'] = np.where(
    orders['delivery_partner_id'].isnull()
    &
    (orders['is_cancelled']=='Y'),
    "Not Assigned",
    np.where(
        orders['delivery_partner_id'].isnull(),
        "Unknown",
        orders['delivery_partner_id']
    )
)

In [60]:
orders.isnull().sum()

order_id               0
customer_id            0
restaurant_id          0
delivery_partner_id    0
order_timestamp        0
subtotal_amount        0
discount_amount        0
delivery_fee           0
total_amount           0
is_cod                 0
is_cancelled           0
dtype: int64

#### Handling Duplicate data

In [61]:
orders.duplicated().sum()

0

In [62]:
orders.drop_duplicates(subset=['order_id'])

,order_id,customer_id,restaurant_id,delivery_partner_id,order_timestamp,subtotal_amount,discount_amount,delivery_fee,total_amount,is_cod,is_cancelled
0,ORD202501023439,CUST181110,REST08622,DP05541,2025-01-01 12:00:00,471.62,35.44,30.56,466.74,N,N
1,ORD202501012051,CUST025572,REST02383,DP08091,2025-01-01 12:00:00,255.68,0.00,27.45,283.13,Y,N
2,ORD202501019281,CUST179306,REST14069,DP02021,2025-01-01 12:00:00,428.38,0.00,26.23,454.61,N,N
3,ORD202501000124,CUST191820,REST19745,DP13859,2025-01-01 12:00:00,260.81,0.00,32.75,293.56,N,N
4,ORD202501006518,CUST033760,REST12962,DP09615,2025-01-01 12:00:00,280.33,0.00,25.57,305.90,N,N
...,...,...,...,...,...,...,...,...,...,...,...
149161,ORD202509003524,CUST080037,REST12269,DP13152,2025-09-30 22:51:00,0.00,0.00,0.00,0.00,N,Y
149162,ORD202509007665,CUST014106,REST04052,Not Assigned,2025-09-30 22:52:00,0.00,0.00,0.00,0.00,Y,Y
149163,ORD202509007687,CUST181895,REST07289,DP04700,2025-09-30 22:55:00,521.08,85.35,20.67,456.40,N,N
149164,ORD202509002029,CUST089114,REST18195,DP12994,2025-09-30 22:58:00,199.13,22.63,20.37,196.87,N,N
149165,ORD202509007649,CUST165574,REST04104,DP09675,2025-09-30 22:59:00,271.90,36.82,39.02,274.11,Y,N

#### Covert datetime

In [63]:
orders['order_timestamp'] = pd.to_datetime(orders['order_timestamp'])

In [64]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149166 entries, 0 to 149165
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             149166 non-null  object
 1   customer_id          149166 non-null  object
 2   restaurant_id        149166 non-null  object
 3   delivery_partner_id  149166 non-null  object
 4   order_timestamp      149166 non-null  datetime64[ns]
 5   subtotal_amount      149166 non-null  float64
 6   discount_amount      149166 non-null  float64
 7   delivery_fee         149166 non-null  float64
 8   total_amount         149166 non-null  float64
 9   is_cod               149166 non-null  object
 10  is_cancelled         149166 non-null  object
dtypes: datetime64[ns](1), float64(4), object(6)
memory usage: 12.5+ MB

In [65]:
orders['order_year'] = orders['order_timestamp'].dt.year

In [66]:
orders['order_month'] = orders['order_timestamp'].dt.month

In [67]:
orders['order_day'] = orders['order_timestamp'].dt.day

In [68]:
orders['week_day'] = orders['order_timestamp'].dt.day_name()

#### Create calculated column

In [69]:
orders['net_revenue'] = orders['subtotal_amount'] - orders['discount_amount'] + orders['delivery_fee']

In [70]:
def crisis_phase(date):
    if date < pd.Timestamp('2025-05-31'):
        return "Pre-crisis"
    elif date < pd.Timestamp('2025-06-30'):
        return "Crisis"
    else:
        return "Recovery"

In [71]:
orders['crisis_phase'] = orders['order_timestamp'].apply(crisis_phase)

In [72]:
orders.head()

,order_id,customer_id,restaurant_id,delivery_partner_id,order_timestamp,subtotal_amount,discount_amount,delivery_fee,total_amount,is_cod,is_cancelled,order_year,order_month,order_day,week_day,net_revenue,crisis_phase
0,ORD202501023439,CUST181110,REST08622,DP05541,2025-01-01 12:00:00,471.62,35.44,30.56,466.74,N,N,2025,1,1,Wednesday,466.74,Pre-crisis
1,ORD202501012051,CUST025572,REST02383,DP08091,2025-01-01 12:00:00,255.68,0.00,27.45,283.13,Y,N,2025,1,1,Wednesday,283.13,Pre-crisis
2,ORD202501019281,CUST179306,REST14069,DP02021,2025-01-01 12:00:00,428.38,0.00,26.23,454.61,N,N,2025,1,1,Wednesday,454.61,Pre-crisis
3,ORD202501000124,CUST191820,REST19745,DP13859,2025-01-01 12:00:00,260.81,0.00,32.75,293.56,N,N,2025,1,1,Wednesday,293.56,Pre-crisis
4,ORD202501006518,CUST033760,REST12962,DP09615,2025-01-01 12:00:00,280.33,0.00,25.57,305.90,N,N,2025,1,1,Wednesday,305.90,Pre-crisis

In [73]:
orders['crisis_phase'].value_counts()

crisis_phase
Pre-crisis    113111
Recovery       26355
Crisis          9700
Name: count, dtype: int64

In [74]:
delivery = pd.read_csv(r"fact_delivery_performance.csv")

In [75]:
delivery.head()

,order_id,actual_delivery_time_mins,expected_delivery_time_mins,distance_km
0,ORD202501023439,31,31,6.4
1,ORD202501012051,46,42,1.9
2,ORD202501019281,25,31,6.2
3,ORD202501000124,29,41,6.2
4,ORD202501006518,37,41,2.4

In [76]:
delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149166 entries, 0 to 149165
Data columns (total 4 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   order_id                     149166 non-null  object
 1   actual_delivery_time_mins    149166 non-null  int64
 2   expected_delivery_time_mins  149166 non-null  int64
 3   distance_km                  149166 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 4.6+ MB

In [77]:
def delay_status(row):
    if row['actual_delivery_time_mins'] > row['expected_delivery_time_mins']:
        return 'Delayed'
    else:
        return 'On_Time'

In [78]:
delivery['delay_status'] = delivery.apply(delay_status, axis=1)

In [79]:
delivery.head()

,order_id,actual_delivery_time_mins,expected_delivery_time_mins,distance_km,delay_status
0,ORD202501023439,31,31,6.4,On_Time
1,ORD202501012051,46,42,1.9,Delayed
2,ORD202501019281,25,31,6.2,On_Time
3,ORD202501000124,29,41,6.2,On_Time
4,ORD202501006518,37,41,2.4,On_Time

In [80]:
delivery['delay_status'].value_counts()

delay_status
Delayed    95226
On_Time    53940
Name: count, dtype: int64

In [81]:
delivery['delivery_delay_mins'] = delivery['actual_delivery_time_mins'] - delivery['expected_delivery_time_mins']

In [82]:
delivery.head()

,order_id,actual_delivery_time_mins,expected_delivery_time_mins,distance_km,delay_status,delivery_delay_mins
0,ORD202501023439,31,31,6.4,On_Time,0
1,ORD202501012051,46,42,1.9,Delayed,4
2,ORD202501019281,25,31,6.2,On_Time,-6
3,ORD202501000124,29,41,6.2,On_Time,-12
4,ORD202501006518,37,41,2.4,On_Time,-4

In [83]:
orders.to_csv('Final_orders.csv')

In [84]:
delivery.to_csv('Final_delivery_performace.csv')